# fly.toml app configuration file generated for qr-stempel on 2026-05-20T17:19:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qr-stempel'
primary_region = 'fra'

[build]

[env]
  PORT = '8000'
  STAMPS_TO_REDEEM = '3'

[[mounts]]
  source = 'qr_stempel_data'
  destination = '/usr/src/app/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
